require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "config.ru"
    - "config/*"
    - "config/**/*"
    - "db/*"
    - "db/migrate/*"
    - "test/*"
    - "test/**/*"
    - "Gemfile"
    - "Rakefile"

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
